FROM ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git cmake ninja-build gcc g++ python3 curl ca-certificates spirv-headers \
    libvulkan-dev python3-venv
# Build glslc (shaderc) from source - needed by ggml-vulkan
RUN git clone --depth 1 https://github.com/google/shaderc /shaderc \
 && cd /shaderc \
 && ./utils/git-sync-deps \
 && cmake -GNinja -B build -DCMAKE_BUILD_TYPE=Release \
      -DSHADERC_SKIP_TESTS=ON -DSHADERC_SKIP_EXAMPLES=ON -DSHADERC_SKIP_DOCS=ON \
 && ninja -C build glslc_exe \
 && install -m755 build/glslc/glslc /usr/local/bin/glslc \
 && glslc --version | head -1
RUN git clone --depth 1 https://github.com/0xShug0/audio.cpp /audio.cpp
WORKDIR /audio.cpp
RUN cd /audio.cpp && ./scripts/build_linux.sh --backend vulkan --model-set custom --models pocket_tts --target audiocpp_cli --target audiocpp_server
